url: https://femontanha.github.io
baseurl: ""

# Site settings
title: femontanha
email: femontanhanew@gmail.com
description: "Front-end Developer located in Brazil"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3498db
  secondary: 2980b9
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Fellipe Azambuja
  pic: http://pbs.twimg.com/profile_images/657406409341030400/4YB5kvoX.jpg
  position: Front-end Developer
  social:
    - title: twitter
      url: http://www.twitter.com/femontanha
    - title: github
      url: http://www.github.com/femontanha
    - title: linkedin
      url: https://br.linkedin.com/in/femontanha

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/femontanha
  - title: linkedin
    url: https://br.linkedin.com/in/femontanha
  - title: github
    url: http://github.com/femontanha

# Build settings
markdown: kramdown
permalink: pretty
